### ISSUE TITLE
Feature Request: Beautify Fingerprint SQL

### ISSUE THREAD

**Issue by plessbd** [devops-works/dw-query-digest#5]
I would find it easier to read if the SQL Fingerprint if it would at least UPPERCASE keywords.

I am not sure if it should add new lines or not (not sure how that would look)

**Comment by leucos** [comment]
Sorry I overlooked this issue @plessbd :(

I moved the project to gitlab and recreated your issue here https://gitlab.com/devopsworks/tools/dw-query-digest/-/issues/1
